---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Docker meta Service Name for docker hub
        id: docker_meta_img
        uses: docker/metadata-action@v5
        with:
          images: docker.io/schulcloud/version-aggregator, quay.io/schulcloudverbund/version-aggregator
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log into docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into quay registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push ${{ github.repository }}
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          pull: true
          tags: ${{ steps.docker_meta_img.outputs.tags }}
          labels: ${{ steps.docker_meta_img.outputs.labels }}
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false


      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.2

      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.docker_meta_img.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
          DIGEST: ${{ steps.build_and_push.outputs.digest }}


  create_release:
      runs-on: ubuntu-latest
      permissions:
          contents: write
      steps:
          - name: generate sbom via dependency-graph
            run: gh api repos/${{ github.repository }}/dependency-graph/sbom > dependencies.sbom.json
            env:
                GH_TOKEN: ${{ github.token }}
          - name: create release
            uses: softprops/action-gh-release@v2
            with:
                files: dependencies.sbom.json